
import React from 'react';
import { Youtube, Facebook, Instagram, Twitter, Globe, Play } from 'lucide-react';

export const CATEGORY_ICONS: Record<string, React.ReactNode> = {
  youtube: <Youtube className="text-red-500" />,
  facebook: <Facebook className="text-blue-500" />,
  instagram: <Instagram className="text-pink-500" />,
  twitter: <Twitter className="text-sky-400" />,
  tiktok: <Play className="text-white fill-current" />,
  other: <Globe className="text-slate-400" />
};

export const MIN_WITHDRAWAL = 250;
export const REFERRAL_BONUS = 5;
export const ACTIVATION_FEE = 30;
export const MIN_REFERRALS_FOR_WITHDRAW = 3;

export const TRANSLATIONS = {
  en: {
    home: "Home",
    tasks: "Tasks",
    wallet: "Wallet",
    profile: "Profile",
    admin_panel: "Panel",
    total_balance: "Total Balance",
    referrals: "Referrals",
    active_opps: "Active Opportunities",
    view_all: "View All Tasks",
    earn_reward: "Earn Reward",
    withdraw: "Withdraw Funds",
    payout_req: "Request Payout",
    amount: "Amount",
    method: "Method",
    wallet_num: "Wallet Number",
    recent_tx: "Recent Transactions",
    support: "Support",
    kyc_status: "KYC Status",
    verify_now: "Verify Now",
    sign_out: "Sign Out",
    welcome_admin: "WELCOME BACK, ADMIN",
    daily_tasks: "Daily Tasks",
    all_platforms: "All Platforms",
    newest: "Newest",
    high_reward: "High Reward",
    pending_verif: "Pending Verification",
    completed: "Task Completed",
    rejected: "Rejected - Try Again",
    launch_task: "Launch Task",
    submit_proof: "Submit Proof",
    instruction: "Step-by-Step Instructions",
    go_target: "GO TO TARGET PAGE",
    copy_caption: "COPY POST CAPTION",
    download_asset: "DOWNLOAD ASSET IMAGE",
    submit_now: "SUBMIT FOR APPROVAL",
    share_code: "SHARE CODE",
    copy_link: "COPY LINK",
    ref_code: "Referral Code",
    ref_link: "Referral Link",
    total_ref: "Total Referrals",
    invite: "Invite Friends",
    bonuses: "Bonuses & Rewards",
    verify_id: "Account Verification",
    identity_verif: "Identity Verification"
  },
  bn: {
    home: "হোম",
    tasks: "কাজসমূহ",
    wallet: "ওয়ালেট",
    profile: "প্রোফাইল",
    admin_panel: "প্যানেল",
    total_balance: "মোট ব্যালেন্স",
    referrals: "রেফারাল",
    active_opps: "চলমান সুযোগ",
    view_all: "সব কাজ দেখুন",
    earn_reward: "পুরস্কার জিতুন",
    withdraw: "টাকা উত্তোলন",
    payout_req: "উত্তোলন অনুরোধ",
    amount: "পরিমাণ",
    method: "পদ্ধতি",
    wallet_num: "ওয়ালেট নম্বর",
    recent_tx: "সাম্প্রতিক লেনদেন",
    support: "সাপোর্ট",
    kyc_status: "KYC অবস্থা",
    verify_now: "ভেরিফাই করুন",
    sign_out: "লগ আউট",
    welcome_admin: "স্বাগতম এডমিন",
    daily_tasks: "দৈনিক কাজ",
    all_platforms: "সব প্ল্যাটফর্ম",
    newest: "নতুনগুলো",
    high_reward: "বেশি ইনকাম",
    pending_verif: "যাচাইধীন আছে",
    completed: "কাজ সম্পন্ন হয়েছে",
    rejected: "বাতিল - আবার চেষ্টা করুন",
    launch_task: "কাজ শুরু করুন",
    submit_proof: "প্রমাণ জমা দিন",
    instruction: "ধাপে ধাপে নির্দেশাবলী",
    go_target: "লিংকে যান",
    copy_caption: "ক্যাপশন কপি করুন",
    download_asset: "ছবি ডাউনলোড করুন",
    submit_now: "জমা দিন",
    share_code: "কোড কপি",
    copy_link: "লিংক কপি",
    ref_code: "রেফারাল কোড",
    ref_link: "রেফারাল লিংক",
    total_ref: "মোট রেফারাল",
    invite: "বন্ধুদের আমন্ত্রণ জানান",
    bonuses: "বোনাস ও পুরস্কার",
    verify_id: "অ্যাকাউন্ট ভেরিফিকেশন",
    identity_verif: "পরিচয় যাচাইকরণ"
  }
};
